import os
import subprocess

from settings import load_settings

RICE_LUA_PATH = os.path.expanduser("~/.config/hypr/lua/generated/theme-sync-rice.lua")


def apply_hyprland_rice() -> None:
    """Regenerate the Dolphin opacity/blur Hyprland rule and reload.

    Independent of the syncDolphin color toggle: opacity/blur are a window
    compositing preference, not part of the KDE color scheme, so they apply
    even if Dolphin's colors are left untouched.
    """
    settings = load_settings()
    opacity_pct = max(40, min(100, int(settings.get("dolphinOpacity", 89))))
    opacity = opacity_pct / 100.0
    inactive = max(0.5, round(opacity - 0.06, 2))
    blur = bool(settings.get("dolphinBlur", True))

    os.makedirs(os.path.dirname(RICE_LUA_PATH), exist_ok=True)
    lua = f"""-- Auto-generated by the positive.theme-sync Ambxst mod. Do not edit by
-- hand -- regenerated whenever the mod's Dolphin opacity/blur settings change.
return {{
    dolphinOpacity = "{opacity:.2f} {inactive:.2f} 1.0",
    dolphinXray = {"false" if blur else "true"},
}}
"""
    tmp = RICE_LUA_PATH + ".tmp"
    with open(tmp, "w") as f:
        f.write(lua)
    os.replace(tmp, RICE_LUA_PATH)

    subprocess.run(["hyprctl", "reload"], capture_output=True, timeout=5)


if __name__ == "__main__":
    apply_hyprland_rice()
