import os, re, subprocess
from .base import BaseTarget
from palette import Palette

class BtopTarget(BaseTarget):
    @property
    def name(self) -> str:
        return "btop"

    def generate(self, palette: Palette) -> None:
        theme_dir = os.path.expanduser("~/.config/btop/themes")
        os.makedirs(theme_dir, exist_ok=True)
        theme_path = os.path.join(theme_dir, "ambxst.theme")

        content = f"""# btop theme dynamically generated by Ambxst wallpaper sync

theme[main_bg]=""
theme[main_fg]="{palette.foreground}"
theme[title]="{palette.accent}"
theme[hi_fg]="{palette.accent}"
theme[selected_bg]="{palette.surface}"
theme[selected_fg]="{palette.foreground}"
theme[inactive_fg]="{palette.dim_fg}"
theme[proc_misc]="{palette.accent}"
theme[cpu_box]="{palette.accent}"
theme[mem_box]="{palette.accent}"
theme[net_box]="{palette.accent}"
theme[proc_box]="{palette.accent}"
theme[div_line]="{palette.surface}"

theme[temp_start]="{palette.dim_accent}"
theme[temp_mid]="{palette.accent}"
theme[temp_end]="#ff5449"

theme[cpu_start]="{palette.dim_accent}"
theme[cpu_mid]="{palette.accent}"
theme[cpu_end]="#ff5449"

theme[free_start]="{palette.dim_accent}"
theme[free_mid]="{palette.accent}"
theme[free_end]="{palette.accent}"
theme[cached_start]="{palette.dim_accent}"
theme[cached_mid]="{palette.accent}"
theme[cached_end]="{palette.accent}"
theme[available_start]="{palette.dim_accent}"
theme[available_mid]="{palette.accent}"
theme[available_end]="{palette.accent}"
theme[used_start]="{palette.dim_accent}"
theme[used_mid]="{palette.accent}"
theme[used_end]="#ff5449"

theme[download_start]="{palette.dim_accent}"
theme[download_mid]="{palette.accent}"
theme[download_end]="{palette.accent}"

theme[upload_start]="{palette.dim_accent}"
theme[upload_mid]="{palette.accent}"
theme[upload_end]="#ff5449"
"""
        with open(theme_path, "w") as f:
            f.write(content)

        # Verify btop.conf uses ambxst theme and transparency
        btop_conf = os.path.expanduser("~/.config/btop/btop.conf")
        if os.path.exists(btop_conf):
            with open(btop_conf, "r") as f:
                bc = f.read()
            changed = False
            if 'color_theme = "ambxst"' not in bc:
                bc = re.sub(r'color_theme\s*=\s*"[^"]*"', 'color_theme = "ambxst"', bc)
                changed = True
            if 'theme_background = false' not in bc:
                bc = re.sub(r'theme_background\s*=\s*\w+', 'theme_background = false', bc)
                changed = True
            if changed:
                with open(btop_conf, "w") as f:
                    f.write(bc)

    def apply(self) -> None:
        # btop supports hot config/theme reloading via SIGUSR2
        subprocess.run(["pkill", "-SIGUSR2", "btop"], capture_output=True)

