import os
from .base import BaseTarget
from palette import Palette

def to_rgba(hex_code: str, alpha: str = "ff") -> str:
    return hex_code.lstrip("#") + alpha

class FuzzelTarget(BaseTarget):
    @property
    def name(self) -> str:
        return "Fuzzel"

    def generate(self, palette: Palette) -> None:
        target_path = os.path.expanduser("~/.config/fuzzel/fuzzel.ini")
        os.makedirs(os.path.dirname(target_path), exist_ok=True)

        bg_rgba = to_rgba(palette.background, "ea")          # Frosted glass background (~92% opacity)
        fg_rgba = to_rgba(palette.foreground, "ff")
        accent_rgba = to_rgba(palette.accent, "ff")          # Shell Material You accent
        dim_fg_rgba = to_rgba(palette.dim_fg, "aa")
        card_rgba = to_rgba(palette.card, "f0")              # Selection highlight pill
        border_rgba = to_rgba(palette.accent, "dd")          # Accent border glow

        content = f"""# ==============================================================================
# Ambxst Dynamic Palette for Fuzzel
# Auto-generated by ambxst-theme-sync
# ==============================================================================

font=JetBrainsMono Nerd Font:size=11
dpi-aware=auto
prompt="󰌆  "
placeholder="Search [Super+Ctrl+B: help]"
lines=8
width=40
tabs=4
horizontal-pad=24
vertical-pad=16
inner-pad=10
layer=overlay
exit-on-keyboard-focus-loss=yes
launch-prefix=hypr-run

[border]
width=2
radius=16
selection-radius=8

[colors]
background={bg_rgba}
text={fg_rgba}
prompt={accent_rgba}
placeholder={dim_fg_rgba}
message={dim_fg_rgba}
counter={dim_fg_rgba}
input={fg_rgba}
match={accent_rgba}
selection={card_rgba}
selection-text={fg_rgba}
selection-match={accent_rgba}
border={border_rgba}

"""
        with open(target_path, "w") as f:
            f.write(content)

    def apply(self) -> None:
        # Fuzzel reads its configuration fresh on every invocation
        pass
