import os, re
from .base import BaseTarget
from palette import Palette

def to_rgba(hex_code: str, alpha: str = "ff") -> str:
    return hex_code.lstrip("#") + alpha

class FuzzelTarget(BaseTarget):
    @property
    def name(self) -> str:
        return "Fuzzel"

    def generate(self, palette: Palette) -> None:
        target_path = os.path.expanduser("~/.config/fuzzel/fuzzel.ini")
        os.makedirs(os.path.dirname(target_path), exist_ok=True)

        bg_rgba = to_rgba(palette.background, "ea")          # Frosted glass background (~92% opacity)
        fg_rgba = to_rgba(palette.foreground, "ff")
        accent_rgba = to_rgba(palette.accent, "ff")          # Shell Material You accent
        dim_fg_rgba = to_rgba(palette.dim_fg, "aa")
        card_rgba = to_rgba(palette.card, "f0")              # Selection highlight pill
        border_rgba = to_rgba(palette.accent, "dd")          # Accent border glow

        colors_block = f"""[colors]
background={bg_rgba}
text={fg_rgba}
prompt={accent_rgba}
placeholder={dim_fg_rgba}
message={dim_fg_rgba}
counter={dim_fg_rgba}
input={fg_rgba}
match={accent_rgba}
selection={card_rgba}
selection-text={fg_rgba}
selection-match={accent_rgba}
border={border_rgba}
"""

        if os.path.exists(target_path):
            # Only touch the [colors] section -- font, layout, border
            # width/radius, prompt symbol, etc. are the user's own to keep.
            with open(target_path, "r") as f:
                content = f.read()
            if "[colors]" in content:
                content = re.sub(r"\[colors\][^\[]*", colors_block, content)
            else:
                content = content.rstrip() + "\n\n" + colors_block
        else:
            content = f"""# ==============================================================================
# Ambxst Dynamic Palette for Fuzzel
# Colors below are auto-generated by ambxst-theme-sync and re-synced on
# every wallpaper change; everything else here is yours to customize freely
# and won't be touched.
# ==============================================================================

font=JetBrainsMono Nerd Font:size=11
dpi-aware=auto
prompt="󰌆  "
placeholder="Search [Super+Ctrl+B: help]"
lines=8
width=40
tabs=4
horizontal-pad=24
vertical-pad=16
inner-pad=10
layer=overlay
exit-on-keyboard-focus-loss=yes
launch-prefix=hypr-run

[border]
width=2
radius=16
selection-radius=8

{colors_block}"""

        with open(target_path, "w") as f:
            f.write(content)

    def apply(self) -> None:
        # Fuzzel reads its configuration fresh on every invocation
        pass
