import subprocess
from .base import BaseTarget
from palette import Palette

class HyprlandTarget(BaseTarget):
    @property
    def name(self) -> str:
        return "Hyprland"

    def generate(self, palette: Palette) -> None:
        # Hyprland lua config is generated by Ambxst directly
        pass

    def apply(self) -> None:
        # Live-update window active border color without restarting compositor
        pass
